apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-72pc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-72pc
    app.kubernetes.io/part-of: tkrw-pr714-0075-0035-app
  name: devfile-sample-72pc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-72pc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-72pc
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0035-tenant/tkrw-pr714-0075-0035-app/devfile-sample-72pc@sha256:5d88bcf0fdbad54628ee939501c8bca61ccb868a1fc5f5b42418370e243128b7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
